### ISSUE TITLE
Question Name

### ISSUE THREAD

**Issue by spuddybike** [CLOSER-Cohorts/colectica_api#8]
question name is held as an AttributePair 
<QuestionItem xmlns="ddi:datacollection:3_2" isUniversallyUnique="true" versionDate="2019-11-18T12:19:15.6285306Z">
<r:URN>
urn:ddi:uk.cls.bcs70:d70babed-d18b-48ce-85a1-43a0041201c3:1
</r:URN>
<r:Agency>uk.cls.bcs70</r:Agency>
<r:ID>d70babed-d18b-48ce-85a1-43a0041201c3</r:ID>
<r:Version>1</r:Version>
<r:UserID typeOfUserID="colectica:sourceId">bcs_80_pqf-qi-101767</r:UserID>
<r:UserAttributePair>
**<r:AttributeKey>extension:Label</r:AttributeKey>
<r:AttributeValue>{"en-GB":"_B13 vi_"}</r:AttributeValue>**
</r:UserAttributePair>

**Comment by jli755** [comment]
Fixed in d2b8459f2ec0584be9b7e2ad33996f203e163a85.
